declare function getTaskStatusDir(status: string): string;
declare function getPendingKindDir(kind: string): string;
declare function getTaskFile(status: string, kind: string, taskId: string): string;
declare function getTaskResultDir(taskId: string): string;
declare function getWorkerStateFile(workerName: string): string;
declare function getWorkerEventFile(date?: Date): string;
declare const _default: {
    WORKERS_ROOT: string;
    TASKS_ROOT: string;
    RESULTS_ROOT: string;
    WORKER_STATE_DIR: string;
    SUPERVISOR_DIR: string;
    getTaskStatusDir: typeof getTaskStatusDir;
    getPendingKindDir: typeof getPendingKindDir;
    getTaskFile: typeof getTaskFile;
    getTaskResultDir: typeof getTaskResultDir;
    getWorkerStateFile: typeof getWorkerStateFile;
    getWorkerEventFile: typeof getWorkerEventFile;
};
export = _default;
