declare function safeCompare(a: any, b: any): any;
declare function isBcryptHash(s: any): boolean;
declare function hashPassword(plain: any): Promise<any>;
declare function verifyPassword(input: any, stored: any, upgradeFile: any): Promise<any>;
declare function getAccessPasswordRecord(): {
    value: any;
    sourceFile: any;
    legacy: boolean;
};
declare function removeLegacyAccessPasswordAfterUpgrade(record: any, input: any): Promise<boolean>;
declare function getAdminPassword(): any;
declare function getAccessPassword(): any;
declare function ensureInitialCredentials(): void;
declare function resetDashboardCredentials(): void;
declare function getSessionSecret(): any;
declare function rotateSessionSecret(): any;
declare function createToken(): string;
declare function validateToken(token: any): any;
declare function createAdminToken(): string;
declare function validateAdminToken(token: any): any;
declare function generateResetToken(): any;
declare function getResetToken(): any;
declare function shouldGenerateResetTokenOnStartup(): boolean;
declare function isSameOriginRequest(req: any): boolean;
declare function isRequestSiteTrusted(req: any): boolean;
declare function applyCorsHeaders(req: any, res: any): void;
declare function rejectCrossSiteRequest(req: any, res: any): boolean;
declare function isLocalAuthBypass(req: any): boolean;
declare function requireAdmin(req: any, res: any): boolean;
declare function requireStrictAdmin(req: any, res: any): boolean;
declare function isLoginRateLimited(ip: any): boolean;
declare function recordLoginFailure(ip: any): void;
declare function clearLoginFails(ip: any): void;
declare function trimLoginFailMap(now?: number): void;
declare const _default: {
    TOKEN_EXPIRY_MS: number;
    safeCompare: typeof safeCompare;
    hashPassword: typeof hashPassword;
    verifyPassword: typeof verifyPassword;
    isBcryptHash: typeof isBcryptHash;
    getAdminPassword: typeof getAdminPassword;
    getAccessPasswordRecord: typeof getAccessPasswordRecord;
    removeLegacyAccessPasswordAfterUpgrade: typeof removeLegacyAccessPasswordAfterUpgrade;
    getAccessPassword: typeof getAccessPassword;
    ensureInitialCredentials: typeof ensureInitialCredentials;
    resetDashboardCredentials: typeof resetDashboardCredentials;
    getSessionSecret: typeof getSessionSecret;
    rotateSessionSecret: typeof rotateSessionSecret;
    createToken: typeof createToken;
    validateToken: typeof validateToken;
    createAdminToken: typeof createAdminToken;
    validateAdminToken: typeof validateAdminToken;
    generateResetToken: typeof generateResetToken;
    getResetToken: typeof getResetToken;
    shouldGenerateResetTokenOnStartup: typeof shouldGenerateResetTokenOnStartup;
    isSameOriginRequest: typeof isSameOriginRequest;
    isRequestSiteTrusted: typeof isRequestSiteTrusted;
    applyCorsHeaders: typeof applyCorsHeaders;
    rejectCrossSiteRequest: typeof rejectCrossSiteRequest;
    isLocalAuthBypass: typeof isLocalAuthBypass;
    requireAdmin: typeof requireAdmin;
    requireStrictAdmin: typeof requireStrictAdmin;
    isLoginRateLimited: typeof isLoginRateLimited;
    recordLoginFailure: typeof recordLoginFailure;
    clearLoginFails: typeof clearLoginFails;
    trimLoginFailMap: typeof trimLoginFailMap;
    loginFailMap: Map<any, any>;
};
export = _default;
