import type { IncomingMessage, ServerResponse } from 'http';
interface AccessPasswordRecord {
    value: string;
    sourceFile: string;
    legacy: boolean;
}
interface LoginFailEntry {
    count: number;
    firstFail: number;
    lockedUntil: number;
}
declare function safeCompare(a: unknown, b: unknown): boolean;
declare function isBcryptHash(s: unknown): boolean;
declare function hashPassword(plain: string): Promise<string>;
declare function verifyPassword(input: string, stored: string, upgradeFile?: string): Promise<boolean>;
declare function getAccessPasswordRecord(): AccessPasswordRecord;
declare function removeLegacyAccessPasswordAfterUpgrade(record: AccessPasswordRecord, input: string): Promise<boolean>;
declare function getAdminPassword(): string;
declare function getAccessPassword(): string;
declare function ensureInitialCredentials(): void;
declare function resetDashboardCredentials(): void;
declare function getSessionSecret(): string;
declare function rotateSessionSecret(): string;
declare function createToken(): string;
declare function validateToken(token: unknown): boolean;
declare function createAdminToken(): string;
declare function validateAdminToken(token: unknown): boolean;
declare function generateResetToken(): string;
declare function getResetToken(): string;
declare function shouldGenerateResetTokenOnStartup(): boolean;
declare function isSameOriginRequest(req: IncomingMessage): boolean;
declare function isRequestSiteTrusted(req: IncomingMessage): boolean;
declare function applyCorsHeaders(req: IncomingMessage, res: ServerResponse): void;
declare function rejectCrossSiteRequest(req: IncomingMessage, res: ServerResponse): boolean;
declare function isLocalAuthBypass(req: IncomingMessage | null | undefined): boolean;
declare function requireAdmin(req: IncomingMessage, res: ServerResponse): boolean;
declare function requireStrictAdmin(req: IncomingMessage, res: ServerResponse): boolean;
declare function isLoginRateLimited(ip: string): boolean;
declare function recordLoginFailure(ip: string): void;
declare function clearLoginFails(ip: string): void;
declare function trimLoginFailMap(now?: number): void;
declare const _default: {
    TOKEN_EXPIRY_MS: number;
    safeCompare: typeof safeCompare;
    hashPassword: typeof hashPassword;
    verifyPassword: typeof verifyPassword;
    isBcryptHash: typeof isBcryptHash;
    getAdminPassword: typeof getAdminPassword;
    getAccessPasswordRecord: typeof getAccessPasswordRecord;
    removeLegacyAccessPasswordAfterUpgrade: typeof removeLegacyAccessPasswordAfterUpgrade;
    getAccessPassword: typeof getAccessPassword;
    ensureInitialCredentials: typeof ensureInitialCredentials;
    resetDashboardCredentials: typeof resetDashboardCredentials;
    getSessionSecret: typeof getSessionSecret;
    rotateSessionSecret: typeof rotateSessionSecret;
    createToken: typeof createToken;
    validateToken: typeof validateToken;
    createAdminToken: typeof createAdminToken;
    validateAdminToken: typeof validateAdminToken;
    generateResetToken: typeof generateResetToken;
    getResetToken: typeof getResetToken;
    shouldGenerateResetTokenOnStartup: typeof shouldGenerateResetTokenOnStartup;
    isSameOriginRequest: typeof isSameOriginRequest;
    isRequestSiteTrusted: typeof isRequestSiteTrusted;
    applyCorsHeaders: typeof applyCorsHeaders;
    rejectCrossSiteRequest: typeof rejectCrossSiteRequest;
    isLocalAuthBypass: typeof isLocalAuthBypass;
    requireAdmin: typeof requireAdmin;
    requireStrictAdmin: typeof requireStrictAdmin;
    isLoginRateLimited: typeof isLoginRateLimited;
    recordLoginFailure: typeof recordLoginFailure;
    clearLoginFails: typeof clearLoginFails;
    trimLoginFailMap: typeof trimLoginFailMap;
    loginFailMap: Map<string, LoginFailEntry>;
};
export = _default;
