declare function isGlobalLocalMode(): boolean;
declare function isPackagedLocalWorkspace(): boolean;
declare function getResourceRoot(): string;
declare function isAgentPathInside(target: unknown, root: unknown): boolean;
declare function toProjectRel(filePath: string): string;
declare function resolveProjectRel(rel: unknown): string;
declare function runtimePath(...parts: string[]): string;
declare const _default: {
    PLUGIN_ROOT: string;
    AI_LIB: string;
    KOISHI_DIR: string;
    KOISHI_PID_FILE: string;
    DATA_DIR: string;
    PERSONAS_DIR: string;
    CORE_DIR: string;
    LORES_DIR: string;
    MODES_DIR: string;
    FE_DIR: string;
    DIST_DIR: string;
    AGENT_CONSOLE_DIR: string;
    AGENT_CONSOLE_DIST_DIR: string;
    PORT: string | number;
    HOST: string;
    PASSWORD: string;
    ADMIN_PASSWORD: string;
    ADMIN_PWD_FILE: string;
    ACCESS_PWD_FILE: string;
    LEGACY_ACCESS_PWD_FILE: string;
    RESET_TOKEN_FILE: string;
    SESSION_SECRET_FILE: string;
    CUSTOM_PROVIDERS_FILE: string;
    FALLBACK_CHAINS_FILE: string;
    DEBUG_LOG_CONFIG_FILE: string;
    LOCAL_DEPLOY_MANIFEST_FILE: string;
    LOCAL_NAPCAT_DIR_FILE: string;
    GALLERY_DIR: string;
    GALLERY_METADATA_FILE: string;
    GALLERY_MAX_BYTES: number;
    GALLERY_MIME_EXT: {
        'image/png': string;
        'image/jpeg': string;
        'image/webp': string;
        'image/gif': string;
    };
    GALLERY_FOIL_STYLES: Set<string>;
    NPM_PROXY_ENV_KEYS: string[];
    MAX_LOG_LIMIT: number;
    isGlobalLocalMode: typeof isGlobalLocalMode;
    isPackagedLocalWorkspace: typeof isPackagedLocalWorkspace;
    getResourceRoot: typeof getResourceRoot;
    isAgentPathInside: typeof isAgentPathInside;
    toProjectRel: typeof toProjectRel;
    resolveProjectRel: typeof resolveProjectRel;
    runtimePath: typeof runtimePath;
};
export = _default;
