declare function isGlobalLocalMode(): boolean;
declare function isPackagedLocalWorkspace(): boolean;
declare function getResourceRoot(): any;
declare function isAgentPathInside(target: any, root: any): any;
declare function toProjectRel(filePath: any): any;
declare function resolveProjectRel(rel: any): any;
declare function runtimePath(...parts: any[]): any;
declare const _default: {
    PLUGIN_ROOT: any;
    AI_LIB: any;
    KOISHI_DIR: any;
    KOISHI_PID_FILE: any;
    DATA_DIR: any;
    PERSONAS_DIR: any;
    CORE_DIR: any;
    LORES_DIR: any;
    MODES_DIR: any;
    FE_DIR: any;
    DIST_DIR: any;
    AGENT_CONSOLE_DIR: any;
    AGENT_CONSOLE_DIST_DIR: any;
    PORT: string | number;
    HOST: string;
    PASSWORD: string;
    ADMIN_PASSWORD: string;
    ADMIN_PWD_FILE: any;
    ACCESS_PWD_FILE: any;
    LEGACY_ACCESS_PWD_FILE: any;
    RESET_TOKEN_FILE: any;
    SESSION_SECRET_FILE: any;
    CUSTOM_PROVIDERS_FILE: any;
    FALLBACK_CHAINS_FILE: any;
    DEBUG_LOG_CONFIG_FILE: any;
    LOCAL_DEPLOY_MANIFEST_FILE: any;
    LOCAL_NAPCAT_DIR_FILE: any;
    GALLERY_DIR: any;
    GALLERY_METADATA_FILE: any;
    GALLERY_MAX_BYTES: number;
    GALLERY_MIME_EXT: {
        'image/png': string;
        'image/jpeg': string;
        'image/webp': string;
        'image/gif': string;
    };
    GALLERY_FOIL_STYLES: Set<string>;
    NPM_PROXY_ENV_KEYS: string[];
    MAX_LOG_LIMIT: number;
    isGlobalLocalMode: typeof isGlobalLocalMode;
    isPackagedLocalWorkspace: typeof isPackagedLocalWorkspace;
    getResourceRoot: typeof getResourceRoot;
    isAgentPathInside: typeof isAgentPathInside;
    toProjectRel: typeof toProjectRel;
    resolveProjectRel: typeof resolveProjectRel;
    runtimePath: typeof runtimePath;
};
export = _default;
