declare function parseSkillPositiveInt(value: string | number | undefined, fallback: number, min: number, max: number): number;
declare function readSkillTextIfSmall(file: string): Promise<string>;
declare function stripSkillFrontmatter(text?: string): string;
declare function getSkillDirectoryFingerprint(dir: string): Promise<string>;
declare function getSkillsContentFingerprint(): Promise<string>;
declare function shouldInjectLore(userText?: string): boolean;
declare function shouldInjectTerraLore(userText?: string): boolean;
declare function loadSkills(): Promise<string[]>;
declare function loadSkillsContentCache(): Promise<void>;
declare function refreshSkillsContentCacheIfChanged(): Promise<boolean>;
declare function getSkillsContentCache(): Record<string, unknown>;
declare function buildTestSystemPrompt(): string;
declare function buildFriendlySystemPrompt(): string;
declare function buildFriendlySafetyFramework(): string;
declare function buildAbusiveSystemPrompt(): string;
declare function getSkillsCount(): number;
declare const _default: {
    parseSkillPositiveInt: typeof parseSkillPositiveInt;
    readSkillTextIfSmall: typeof readSkillTextIfSmall;
    stripSkillFrontmatter: typeof stripSkillFrontmatter;
    getSkillDirectoryFingerprint: typeof getSkillDirectoryFingerprint;
    getSkillsContentFingerprint: typeof getSkillsContentFingerprint;
    loadSkills: typeof loadSkills;
    loadSkillsContentCache: typeof loadSkillsContentCache;
    refreshSkillsContentCacheIfChanged: typeof refreshSkillsContentCacheIfChanged;
    getSkillsCount: typeof getSkillsCount;
    getSkillsContentCache: typeof getSkillsContentCache;
    buildTestSystemPrompt: typeof buildTestSystemPrompt;
    buildFriendlySystemPrompt: typeof buildFriendlySystemPrompt;
    buildFriendlySafetyFramework: typeof buildFriendlySafetyFramework;
    buildAbusiveSystemPrompt: typeof buildAbusiveSystemPrompt;
    shouldInjectLore: typeof shouldInjectLore;
    shouldInjectTerraLore: typeof shouldInjectTerraLore;
};
export = _default;
