import type { IncomingMessage, ServerResponse } from 'http';
type AgentRegexRouteHandler = (req: IncomingMessage, res: ServerResponse, match: RegExpMatchArray, pathname: string, url: URL) => void | Promise<void>;
interface AgentRegexRoute {
    pattern: RegExp;
    method: string;
    handler: AgentRegexRouteHandler;
}
declare function handleGetAgentConfig(req: IncomingMessage, res: ServerResponse): Promise<void>;
declare function handlePutAgentConfig(req: IncomingMessage, res: ServerResponse): Promise<void>;
declare function handleGetAgentPersonas(req: IncomingMessage, res: ServerResponse): void;
declare function handlePutAgentPersona(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetTtsVoices(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostTtsClone(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostTtsPreview(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostTtsCloneRename(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostTtsCloneDelete(req: IncomingMessage, res: ServerResponse): void;
declare function handlePutPersonaVoice(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentStats(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentQueue(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentFiles(req: IncomingMessage, res: ServerResponse, pathname: string, url: URL): Promise<void>;
declare function handleGetAgentFile(req: IncomingMessage, res: ServerResponse, pathname: string, url: URL): Promise<void>;
declare function handleGetAgentFileDownload(req: IncomingMessage, res: ServerResponse, pathname: string, url: URL): Promise<void>;
declare function handlePostAgentFileUpload(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentEnv(req: IncomingMessage, res: ServerResponse): Promise<void>;
declare function handleGetAgentShellGuard(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentPlans(req: IncomingMessage, res: ServerResponse): Promise<void>;
declare function handlePostAgentPlans(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentPushLog(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentCrons(req: IncomingMessage, res: ServerResponse): Promise<void>;
declare function handlePostAgentCrons(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetAgentSessions(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostAgentChat(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostAgentConfirm(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostAgentReject(req: IncomingMessage, res: ServerResponse): void;
declare const _default: {
    routes: {
        'GET /dashboard/api/agent/config': typeof handleGetAgentConfig;
        'PUT /dashboard/api/agent/config': typeof handlePutAgentConfig;
        'GET /dashboard/api/agent/personas': typeof handleGetAgentPersonas;
        'PUT /dashboard/api/agent/persona': typeof handlePutAgentPersona;
        'GET /dashboard/api/agent/tts/voices': typeof handleGetTtsVoices;
        'POST /dashboard/api/agent/tts/clone': typeof handlePostTtsClone;
        'POST /dashboard/api/agent/tts/preview': typeof handlePostTtsPreview;
        'POST /dashboard/api/agent/tts/clone/rename': typeof handlePostTtsCloneRename;
        'POST /dashboard/api/agent/tts/clone/delete': typeof handlePostTtsCloneDelete;
        'PUT /dashboard/api/agent/persona/voice': typeof handlePutPersonaVoice;
        'GET /dashboard/api/agent/stats': typeof handleGetAgentStats;
        'GET /dashboard/api/agent/queue': typeof handleGetAgentQueue;
        'GET /dashboard/api/agent/files': typeof handleGetAgentFiles;
        'GET /dashboard/api/agent/file': typeof handleGetAgentFile;
        'GET /dashboard/api/agent/file/download': typeof handleGetAgentFileDownload;
        'POST /dashboard/api/agent/file/upload': typeof handlePostAgentFileUpload;
        'GET /dashboard/api/agent/env': typeof handleGetAgentEnv;
        'GET /dashboard/api/agent/shell-guard': typeof handleGetAgentShellGuard;
        'GET /dashboard/api/agent/plans': typeof handleGetAgentPlans;
        'POST /dashboard/api/agent/plans': typeof handlePostAgentPlans;
        'GET /dashboard/api/agent/push-log': typeof handleGetAgentPushLog;
        'GET /dashboard/api/agent/crons': typeof handleGetAgentCrons;
        'POST /dashboard/api/agent/crons': typeof handlePostAgentCrons;
        'GET /dashboard/api/agent/sessions': typeof handleGetAgentSessions;
        'POST /dashboard/api/agent/chat': typeof handlePostAgentChat;
        'POST /dashboard/api/agent/confirm': typeof handlePostAgentConfirm;
        'POST /dashboard/api/agent/reject': typeof handlePostAgentReject;
    };
    regexRoutes: AgentRegexRoute[];
    getAgentEnvStatus: typeof import("../agent-workspace").getAgentEnvStatus;
};
export = _default;
