declare function getAgentEnvStatus(): {
    name: any;
    exists: any;
    configured: boolean;
    size: number;
}[];
declare function handleGetAgentConfig(req: any, res: any): Promise<any>;
declare function handlePutAgentConfig(req: any, res: any): Promise<void>;
declare function handleGetAgentPersonas(req: any, res: any): any;
declare function handlePutAgentPersona(req: any, res: any): void;
declare function handleGetTtsVoices(req: any, res: any): any;
declare function handlePostTtsClone(req: any, res: any): void;
declare function handlePostTtsPreview(req: any, res: any): void;
declare function handlePostTtsCloneRename(req: any, res: any): void;
declare function handlePostTtsCloneDelete(req: any, res: any): void;
declare function handlePutPersonaVoice(req: any, res: any): void;
declare function handleGetAgentStats(req: any, res: any): any;
declare function handleGetAgentQueue(req: any, res: any): any;
declare function handleGetAgentFiles(req: any, res: any, pathname: any, url: any): Promise<any>;
declare function handleGetAgentFile(req: any, res: any, pathname: any, url: any): Promise<any>;
declare function handleGetAgentFileDownload(req: any, res: any, pathname: any, url: any): Promise<any>;
declare function handlePostAgentFileUpload(req: any, res: any): void;
declare function handleGetAgentEnv(req: any, res: any): Promise<any>;
declare function handleGetAgentShellGuard(req: any, res: any): any;
declare function handleGetAgentPlans(req: any, res: any): Promise<any>;
declare function handlePostAgentPlans(req: any, res: any): void;
declare function handleGetAgentPushLog(req: any, res: any): any;
declare function handleGetAgentCrons(req: any, res: any): Promise<any>;
declare function handlePostAgentCrons(req: any, res: any): void;
declare function handleGetAgentSessions(req: any, res: any): any;
declare function handlePostAgentChat(req: any, res: any): void;
declare function handlePostAgentConfirm(req: any, res: any): void;
declare function handlePostAgentReject(req: any, res: any): void;
declare const _default: {
    routes: {
        'GET /dashboard/api/agent/config': typeof handleGetAgentConfig;
        'PUT /dashboard/api/agent/config': typeof handlePutAgentConfig;
        'GET /dashboard/api/agent/personas': typeof handleGetAgentPersonas;
        'PUT /dashboard/api/agent/persona': typeof handlePutAgentPersona;
        'GET /dashboard/api/agent/tts/voices': typeof handleGetTtsVoices;
        'POST /dashboard/api/agent/tts/clone': typeof handlePostTtsClone;
        'POST /dashboard/api/agent/tts/preview': typeof handlePostTtsPreview;
        'POST /dashboard/api/agent/tts/clone/rename': typeof handlePostTtsCloneRename;
        'POST /dashboard/api/agent/tts/clone/delete': typeof handlePostTtsCloneDelete;
        'PUT /dashboard/api/agent/persona/voice': typeof handlePutPersonaVoice;
        'GET /dashboard/api/agent/stats': typeof handleGetAgentStats;
        'GET /dashboard/api/agent/queue': typeof handleGetAgentQueue;
        'GET /dashboard/api/agent/files': typeof handleGetAgentFiles;
        'GET /dashboard/api/agent/file': typeof handleGetAgentFile;
        'GET /dashboard/api/agent/file/download': typeof handleGetAgentFileDownload;
        'POST /dashboard/api/agent/file/upload': typeof handlePostAgentFileUpload;
        'GET /dashboard/api/agent/env': typeof handleGetAgentEnv;
        'GET /dashboard/api/agent/shell-guard': typeof handleGetAgentShellGuard;
        'GET /dashboard/api/agent/plans': typeof handleGetAgentPlans;
        'POST /dashboard/api/agent/plans': typeof handlePostAgentPlans;
        'GET /dashboard/api/agent/push-log': typeof handleGetAgentPushLog;
        'GET /dashboard/api/agent/crons': typeof handleGetAgentCrons;
        'POST /dashboard/api/agent/crons': typeof handlePostAgentCrons;
        'GET /dashboard/api/agent/sessions': typeof handleGetAgentSessions;
        'POST /dashboard/api/agent/chat': typeof handlePostAgentChat;
        'POST /dashboard/api/agent/confirm': typeof handlePostAgentConfirm;
        'POST /dashboard/api/agent/reject': typeof handlePostAgentReject;
    };
    regexRoutes: {
        pattern: RegExp;
        method: string;
        handler: (req: any, res: any, match: any) => void;
    }[];
    getAgentEnvStatus: typeof getAgentEnvStatus;
};
export = _default;
