declare function handleGetDeployConfig(req: any, res: any): any;
declare function handleGetCheckUpdate(req: any, res: any): any;
declare function handlePutDeployConfig(req: any, res: any): void;
declare function handlePostDeployRun(req: any, res: any): void;
declare function handleGetDeployProgress(req: any, res: any, pathname: any): any;
declare function handlePostFrontendRebuild(req: any, res: any): any;
declare function handleGetFrontendRebuildStatus(req: any, res: any): any;
declare function handlePostDeployConfirm(req: any, res: any): void;
declare function handlePostDeployUpload(req: any, res: any): void;
declare function handlePostDeployLocal(req: any, res: any): void;
declare function handleGetLocalConfigPreview(req: any, res: any): any;
declare function handlePostLocalConfigDelete(req: any, res: any): void;
declare function handleGetLocalUninstallPreview(req: any, res: any): any;
declare function handlePostLocalUninstall(req: any, res: any): void;
declare function handlePostNapcatDownload(req: any, res: any): void;
declare function handlePostNapcatWindowsDownload(req: any, res: any): void;
declare function handlePostNodeWindowsInstall(req: any, res: any): void;
declare function handlePostNpmInstall(req: any, res: any): any;
declare function handlePostNpmRepairAndInstall(req: any, res: any): any;
declare function handleGetNpmInstallStatus(req: any, res: any): any;
declare function handlePostNapcatStart(req: any, res: any): any;
declare function handleGetNapcatStatus(req: any, res: any): any;
declare function handlePostKoishiStart(req: any, res: any): any;
declare function handleGetKoishiStatus(req: any, res: any): any;
declare function handleGetLocalReadyCheck(req: any, res: any): any;
declare function handleGetEnvCheck(req: any, res: any): any;
declare function handleGetBotLocalStatus(req: any, res: any): any;
declare function handlePostBotLocalStop(req: any, res: any): any;
declare const _default: {
    routes: {
        'GET /dashboard/api/deploy/config': typeof handleGetDeployConfig;
        'GET /dashboard/api/deploy/check-update': typeof handleGetCheckUpdate;
        'PUT /dashboard/api/deploy/config': typeof handlePutDeployConfig;
        'POST /dashboard/api/deploy/run': typeof handlePostDeployRun;
        'POST /dashboard/api/deploy/confirm': typeof handlePostDeployConfirm;
        'POST /dashboard/api/deploy/upload': typeof handlePostDeployUpload;
        'POST /dashboard/api/deploy/local': typeof handlePostDeployLocal;
        'GET /dashboard/api/deploy/local-config-preview': typeof handleGetLocalConfigPreview;
        'POST /dashboard/api/deploy/local-config-delete': typeof handlePostLocalConfigDelete;
        'GET /dashboard/api/deploy/local-uninstall-preview': typeof handleGetLocalUninstallPreview;
        'POST /dashboard/api/deploy/local-uninstall': typeof handlePostLocalUninstall;
        'POST /dashboard/api/deploy/napcat-download': typeof handlePostNapcatDownload;
        'POST /dashboard/api/deploy/napcat-windows-download': typeof handlePostNapcatWindowsDownload;
        'POST /dashboard/api/deploy/node-windows-install': typeof handlePostNodeWindowsInstall;
        'POST /dashboard/api/deploy/npm-install': typeof handlePostNpmInstall;
        'POST /dashboard/api/deploy/npm-repair-and-install': typeof handlePostNpmRepairAndInstall;
        'GET /dashboard/api/deploy/npm-install-status': typeof handleGetNpmInstallStatus;
        'POST /dashboard/api/deploy/napcat-start': typeof handlePostNapcatStart;
        'GET /dashboard/api/deploy/napcat-status': typeof handleGetNapcatStatus;
        'POST /dashboard/api/deploy/koishi-start': typeof handlePostKoishiStart;
        'GET /dashboard/api/deploy/koishi-status': typeof handleGetKoishiStatus;
        'GET /dashboard/api/deploy/local-ready-check': typeof handleGetLocalReadyCheck;
        'GET /dashboard/api/env/check': typeof handleGetEnvCheck;
        'POST /dashboard/api/frontend/rebuild': typeof handlePostFrontendRebuild;
        'GET /dashboard/api/frontend/rebuild-status': typeof handleGetFrontendRebuildStatus;
        'GET /dashboard/api/bot/local-status': typeof handleGetBotLocalStatus;
        'POST /dashboard/api/bot/local-stop': typeof handlePostBotLocalStop;
    };
    prefixRoutes: {
        prefix: string;
        method: string;
        handler: typeof handleGetDeployProgress;
    }[];
};
export = _default;
