import type { IncomingMessage, ServerResponse } from 'http';
type DeployRouteHandler = (req: IncomingMessage, res: ServerResponse, pathname: string, url: URL) => void | Promise<void>;
interface DeployPrefixRoute {
    prefix: string;
    method: string;
    handler: DeployRouteHandler;
}
declare function handleGetDeployConfig(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostDeployPreview(req: IncomingMessage, res: ServerResponse): void;
declare function handlePutDeployConfig(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostSafeDeployRun(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostFrontendRebuild(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetFrontendRebuildStatus(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostDeployUpload(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostDeployLocal(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetLocalConfigPreview(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostLocalConfigDelete(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetLocalUninstallPreview(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostLocalUninstall(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNapcatDownload(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNapcatWindowsDownload(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNodeWindowsInstall(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNpmInstall(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNpmRepairAndInstall(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetNpmInstallStatus(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostNapcatStart(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetNapcatStatus(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostKoishiStart(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetKoishiStatus(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetLocalReadyCheck(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetEnvCheck(req: IncomingMessage, res: ServerResponse): void;
declare function handleGetBotLocalStatus(req: IncomingMessage, res: ServerResponse): void;
declare function handlePostBotLocalStop(req: IncomingMessage, res: ServerResponse): void;
declare const _default: {
    routes: {
        'GET /dashboard/api/deploy/config': typeof handleGetDeployConfig;
        'POST /dashboard/api/deploy/preview': typeof handlePostDeployPreview;
        'PUT /dashboard/api/deploy/config': typeof handlePutDeployConfig;
        'POST /dashboard/api/deploy/run': typeof handlePostSafeDeployRun;
        'POST /dashboard/api/deploy/upload': typeof handlePostDeployUpload;
        'POST /dashboard/api/deploy/local': typeof handlePostDeployLocal;
        'GET /dashboard/api/deploy/local-config-preview': typeof handleGetLocalConfigPreview;
        'POST /dashboard/api/deploy/local-config-delete': typeof handlePostLocalConfigDelete;
        'GET /dashboard/api/deploy/local-uninstall-preview': typeof handleGetLocalUninstallPreview;
        'POST /dashboard/api/deploy/local-uninstall': typeof handlePostLocalUninstall;
        'POST /dashboard/api/deploy/napcat-download': typeof handlePostNapcatDownload;
        'POST /dashboard/api/deploy/napcat-windows-download': typeof handlePostNapcatWindowsDownload;
        'POST /dashboard/api/deploy/node-windows-install': typeof handlePostNodeWindowsInstall;
        'POST /dashboard/api/deploy/npm-install': typeof handlePostNpmInstall;
        'POST /dashboard/api/deploy/npm-repair-and-install': typeof handlePostNpmRepairAndInstall;
        'GET /dashboard/api/deploy/npm-install-status': typeof handleGetNpmInstallStatus;
        'POST /dashboard/api/deploy/napcat-start': typeof handlePostNapcatStart;
        'GET /dashboard/api/deploy/napcat-status': typeof handleGetNapcatStatus;
        'POST /dashboard/api/deploy/koishi-start': typeof handlePostKoishiStart;
        'GET /dashboard/api/deploy/koishi-status': typeof handleGetKoishiStatus;
        'GET /dashboard/api/deploy/local-ready-check': typeof handleGetLocalReadyCheck;
        'GET /dashboard/api/env/check': typeof handleGetEnvCheck;
        'POST /dashboard/api/frontend/rebuild': typeof handlePostFrontendRebuild;
        'GET /dashboard/api/frontend/rebuild-status': typeof handleGetFrontendRebuildStatus;
        'GET /dashboard/api/bot/local-status': typeof handleGetBotLocalStatus;
        'POST /dashboard/api/bot/local-stop': typeof handlePostBotLocalStop;
    };
    prefixRoutes: DeployPrefixRoute[];
};
export = _default;
