import type { IncomingMessage, ServerResponse } from 'http';
type RouteHandler = (req: IncomingMessage, res: ServerResponse, pathname: string, url: URL) => unknown;
type ManagementModule<Name extends import('koishi-plugin-dongxuelian-ai/lib/public/management-runtime').ManagementModuleName> = import('koishi-plugin-dongxuelian-ai/lib/public/management-runtime').ManagementModule<Name>;
type ResourceTaskLike = ReturnType<ManagementModule<'resource.taskStore'>['listResourceTasks']>[number];
interface ResourceModuleSet {
    gate: ManagementModule<'resource.gate'>;
    scheduler: ManagementModule<'resource.snapshot'>;
    mode: ManagementModule<'resource.serverModePolicy'>;
    tasks: ManagementModule<'resource.taskStore'>;
    supervisor: ManagementModule<'resource.workerSupervisor'>;
    precompute: ManagementModule<'resource.precomputeStatus'>;
    media: ManagementModule<'resource.mediaQueue'>;
    system: ManagementModule<'resource.systemProtection'>;
    files: ManagementModule<'resource.files'>;
}
declare function normalizeMemoryRange(value: unknown): string;
declare function collectMemoryHistory(mods: ResourceModuleSet, range: string): {
    ok: boolean;
    range: string;
    rangeMs: number;
    bucketMs: number;
    hostSampleIntervalMs: number;
    uiRefreshMs: number;
    retentionMs: number;
    pointCount: number;
    parsedLineCount: number;
    fileCount: number;
    cacheTtlMs: number;
    sources: string[];
    points: {
        ts: number;
        createdAt: string;
        memAvailableMb: number;
        minAvailableMb: number;
        maxAvailableMb: number;
        memUsedMb: number | null;
        minUsedMb: number | null;
        maxUsedMb: number | null;
        memTotalMb: number | null;
        rssMb: number | null;
        sampleCount: number;
        sources: string[];
    }[];
};
declare function getCachedMemoryHistory(mods: ResourceModuleSet, range: string): unknown;
declare function collectDiskUsage(): Record<string, unknown>;
declare function getCachedDiskUsage(): unknown;
declare function sanitizeTask(task: ResourceTaskLike): {
    id: string;
    kind: string;
    status: import("koishi-plugin-dongxuelian-ai/lib/resource-workers/task-types").ResourceTaskStatus;
    source: string;
    channelKey: string;
    userId: string;
    priority: number;
    createdAt: string;
    updatedAt: string;
    expiresAt: string;
    timeoutMs: number;
    step: string | undefined;
    claimedBy: string | undefined;
    claimedAt: string | undefined;
    startedAt: string | undefined;
    finishedAt: string | undefined;
    notify: import("koishi-plugin-dongxuelian-ai/lib/resource-workers/task-types").ResourceTaskNotify;
    error: string | undefined;
    payloadKeys: string[];
};
declare function buildResourceStatus(mods: ResourceModuleSet): Record<string, unknown>;
declare const _default: {
    routes: Record<string, RouteHandler>;
    buildResourceStatus: typeof buildResourceStatus;
    sanitizeTask: typeof sanitizeTask;
    collectMemoryHistory: typeof collectMemoryHistory;
    normalizeMemoryRange: typeof normalizeMemoryRange;
    getCachedMemoryHistory: typeof getCachedMemoryHistory;
    collectDiskUsage: typeof collectDiskUsage;
    getCachedDiskUsage: typeof getCachedDiskUsage;
};
export = _default;
